services:

  # migrator:
  #   build: ./migrations_init
  #   env_file:
  #     - .env
  #     - .env-supabase

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8502:8000"
    env_file:
      - .env
      - .env-supabase
    networks:
      - shared_network
      - default

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - shared_network
      - default
    env_file:
      - .env
      - .env-supabase

  web3:
    build: ./web3auth-g
    volumes:
      - ./web3auth-g:/app
    ports:
      - "8503:5173"
    networks:
      - shared_network
      - default
    environment:
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173



  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password

  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - shared_network


networks:
  shared_network:
    external: true
