services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8502:8000"
    env_file:
      - .env
    networks:
      - app-network


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - app-network
    env_file:
      - .env


networks:
  app-network:
    driver: bridge
