services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8502:8000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - app-network
    env_file:
      - .env

  web3solana:
    build: ./web3solana
    volumes:
      - ./web3solana:/app
    ports:
      - "8503:3000"
    networks:
      - app-network
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Port pour les connexions AMQP
      - "15672:15672"   # Interface de gestion Web
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
