services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8502:8000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - app-network
    env_file:
      - .env

  web3solana:
    build: ./web3solana
    volumes:
      - ./web3solana:/app
    ports:
      - "8503:3000"  # Expose l'API web
    networks:
      - app-network
    env_file:
      - .env


networks:
  app-network:
    driver: bridge
